export const styles = {
  checkInFormControl: (isCalendarOpen: boolean) => ({
    zIndex: 91,
    p: isCalendarOpen ? 2 : 1,
    borderTop: isCalendarOpen ? '2px solid black' : 'none',
    borderBottom: isCalendarOpen ? '2px solid black' : 'none',
    borderLeft: isCalendarOpen ? '2px solid black' : 'none',
    borderRight: isCalendarOpen
      ? '2px solid black'
      : '2px solid rgb(221, 221, 221)',
    borderRadius: isCalendarOpen ? '8px' : 0,
    borderTopEndRadius: 0,
    borderBottomEndRadius: 0,
    cursor: 'pointer',
  }),
  checkOutFormControl: (isCalendarOpen: boolean) => ({
    zIndex: 91,
    p: isCalendarOpen ? 2 : 1,
    ml: isCalendarOpen ? 0 : 2,
    cursor: 'pointer',
    borderTop: isCalendarOpen ? '2px solid black' : 'none',
    borderBottom: isCalendarOpen ? '2px solid black' : 'none',
    borderLeft: 'none',
    borderRight: isCalendarOpen ? '2px solid black' : 'none',
    borderRadius: isCalendarOpen ? '8px' : 0,
    marginLeft: 0,
    borderTopLeftRadius: 0,
    borderBottomLeftRadius: 0,
    paddingLeft: 3,
  }),
  calendarBox: (isCalendarOpen: boolean, rightValue: number) => ({
    position: 'absolute',
    display: isCalendarOpen ? 'block' : 'none',
    zIndex: 90,
    width: '661px',
    right: rightValue,
    top: 20,
    background: 'white',
    p: '24px 32px 16px 32px',
    boxShadow: 'rgba(0, 0, 0, 0.2) 0px 6px 20px',
    borderRadius: '16px',
  }),
  text: {
    fontSize: '2xl',
    fontWeight: 'semibold',
    alignSelf: 'flex-start',
  },
  vStackInner: {
    border: '1px solid rgb(221, 221, 221)',
    borderRadius: '12px',
  },
  hStack: {
    justifyContent: 'space-between',
    w: 'full',
    gap: 0,
    p: 1,
  },
  formLabel: {
    fontSize: '12px',
    mb: 0,
    cursor: 'pointer',
  },
  input: {
    fontSize: '0.875rem',
    outline: 'none',
    border: 'none',
    p: 0,
    height: 'auto',
    cursor: 'pointer',
    _focusVisible: {
      border: 'none',
      boxShadow: 'none',
      pointerEvents: 'none',
    },
    pointerEvents: 'none',
  },
};
